title: "For a new hermeneutics of practice in digital public history: thinkering with memorecord.uni.lu (snippet)"
author: Anita Lucchesi
copyright: "2025"
# logo: logo.png

repository:
  url: https://github.com/digital-monographs/sample-chapter
html:
  use_repository_button: true
  use_issues_button: true

execute:
  execute_notebooks: 'off'
